[build]
  publish = "dist"
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  GEMINI_API_KEY = "AIzaSyAPBDKDl0x1a-w3PZ3GClCUgc8-V331_5M"
